version: "3"

services:
  app:
    image: golang:1.6.1-alpine
    volumes:
      - .:/go/src/goRank
    working_dir: /go/src/goRank
    command: go run app/goRank.go
    ports:
      - "8000:8000"
    depends_on:
      - elastic
  elastic:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2